server:
  port: 8081
spring:
  data:
    mongodb:
      uri: mongodb://192.168.2.10:27017/test

kafka:
  bootstrap-servers: 192.168.2.10:9092
  security-protocol: PLAINTEXT
  senderTopic: orders
  listenerTopic: orderStatus
  groupId: orders
