server:
  port: 8082
kafka:
  bootstrap-servers: 192.168.2.10:9092
  security-protocol: PLAINTEXT
  senderTopic: orderStatus
  listenerTopic: orders
  groupId: kitchen
spring:
  zipkin:
    service:
      name: kitchen
    baseUrl: http://192.168.2.10:9411/
  application:
    name: kitchen
  sleuth:
    sampler:
      probability: 1.0
    web:
      skip-pattern: (^cleanup.*)
    enabled: true
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true